---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/pulumi/pulumi version
    register: pulumi_test_output
  - name: pulumi version
    debug:
      msg: '{{ pulumi_test_output.stdout }}'
