---
- name: Testing andrewrothstein.pulumi
  hosts: all
  tasks:
    - name: Installing andrewrothstein.pulumi
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'pulumi version'
      ansible.builtin.command: /usr/local/pulumi/pulumi version
      changed_when: false
      register: pulumi_test_output
    - name: Output from 'pulumi version'
      ansible.builtin.debug:
        msg: '{{ pulumi_test_output.stdout }}'
