---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for install in {{ pulumi_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ pulumi_install_dir }}'
  changed_when: false
  register: pulumi_binary
- name: Downloading and installing pulumi
  when: not pulumi_binary.stat.exists
  block:
    - name: Downloading {{ pulumi_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ pulumi_url }}'
        dest: '{{ pulumi_tmp_archive }}'
        mode: '644'
        checksum: '{{ pulumi_checksum }}'
    - name: Mkdir {{ pulumi_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ pulumi_install_dir }}'
        mode: '755'
        state: directory
    - name: Unarchive to {{ pulumi_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ pulumi_tmp_archive }}'
        dest: '{{ pulumi_install_dir }}'
        creates: '{{ pulumi_install_subdir }}'
    - name: Fix permissions on {{ pulumi_install_subdir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ pulumi_install_subdir }}'
        mode: '755'
  always:
    - name: Cleanup {{ pulumi_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ pulumi_tmp_archive }}'
        state: absent
- name: Linking {{ pulumi_link_dir }} to {{ pulumi_install_subdir }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ pulumi_install_subdir }}'
    dest: '{{ pulumi_link_dir }}'
    state: link
- name: Add to default path
  become: true
  become_user: root
  with_items:
    - f: pulumi.sh
      d: /etc/profile.d
  ansible.builtin.template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("0644") }}'
